#!/bin/sh

CAMNAME2="Camd3"

case "$1" in
	start)
		echo "[SCRIPT] $1: Starting $CAMNAME2"
		/var/bin/camd3 &
		;;
	stop)
		echo "[SCRIPT] $1: Stopping $CAMNAME2"
		/var/bin/pcamd -kill >/dev/null 2>&1
		# camd3 does not always seems to stop
		usleep 100000
		pids=`pidof camd3`
		if [ -n "$pids" ] ; then
			kill -9 $pids > /dev/null 2>&1
		fi
		;;
	*)
		$0 stop
		exit 1
		;;
esac

exit 0
