#!/bin/sh

if [ -f /lib/modules/$(uname -r)/.reload_modules ] ; then
	$RMMOD $MODDIR/extra/head.ko
fi

$INSMOD $MODDIR/extra/head.ko

#set environment variables (mID)
. /proc/bus/dbox.sh

if [ $mID -eq 05 ] ; then
	if [ -f /lib/modules/$(uname -r)/.reload_modules ] ; then
		if [ -f /lib/modules/$(uname -r)/kernel/fs/reiserfs/reiserfs.ko ] ; then
			$RMMOD $MODDIR/kernel/fs/reiserfs/reiserfs.ko
		fi
		if [ -f /lib/modules/$(uname -r)/kernel/fs/cifs/cifs.ko ] ; then
			$RMMOD $MODDIR/kernel/fs/cifs/cifs.ko
		fi
		if [ -f /lib/modules/$(uname -r)/kernel/fs/smbfs/smbfs.ko ] ; then
			$RMMOD $MODDIR/kernel/fs/smbfs/smbfs.ko
		fi
		if [ -f /lib/modules/$(uname -r)/kernel/drivers/scsi/sg.ko ] ; then
			$RMMOD $MODDIR/kernel/drivers/scsi/sg.ko
		fi
		if [ -f /lib/modules/$(uname -r)/kernel/drivers/usb/input/hid.ko ] ; then
			$RMMOD $MODDIR/kernel/drivers/usb/input/hid.ko
		fi
	fi
fi

if [ $mID -eq 05 ] ; then
	if [ -f /lib/modules/$(uname -r)/kernel/fs/reiserfs/reiserfs.ko ] ; then
		$INSMOD $MODDIR/kernel/fs/reiserfs/reiserfs.ko
	fi
	if [ -f /lib/modules/$(uname -r)/kernel/fs/cifs/cifs.ko ] ; then
		$INSMOD $MODDIR/kernel/fs/cifs/cifs.ko
	fi
	if [ -f /lib/modules/$(uname -r)/kernel/fs/smbfs/smbfs.ko ] ; then
		$INSMOD $MODDIR/kernel/fs/smbfs/smbfs.ko
	fi
	if [ -f /lib/modules/$(uname -r)/kernel/drivers/scsi/sg.ko ] ; then
		$INSMOD $MODDIR/kernel/drivers/scsi/sg.ko
	fi
	if [ -f /lib/modules/$(uname -r)/kernel/drivers/usb/input/hid.ko ] ; then
		$INSMOD $MODDIR/kernel/drivers/usb/input/hid.ko
	fi
fi

#create compatibility links for hardware with only one demux
if [ ! -e /dev/dvb/card0/demux1 ] ; then
	ln -sf /dev/dvb/card0/demux0 /dev/dvb/card0/demux1
	ln -sf /dev/dvb/card0/dvr0 /dev/dvb/card0/dvr1
fi

exit 0
